version: 2
jobs:
  build:
    docker:
      - image: circleci/php
    steps:
      - checkout
      - run: php batch.php
      - persist_to_workspace:
         root: public
         paths:
           - ./*
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7a:db:bc:00:21:97:19:20:1c:9e:18:78:29:0c:2f:fd"
      - attach_workspace:
          at: public
      - run: git clone -b gh-pages git@github.com:mikkame/12contrib.git
      - run: rm -rf 12contrib/*
      - run: cp -rf public/* 12contrib
      - run: cd 12contrib;git config --local user.name "mikkame"; git config --local user.email "matchasoft.jp@gmail.com"
      - run: cd 12contrib; git add ./; git commit -m "From `git log --oneline origin/master -n 1`"; git push
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build